

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CertelEntities : DbContext
{
    public CertelEntities()
        : base("name=CertelEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Aparato> Aparato { get; set; }

    public virtual DbSet<Caracteristica> Caracteristica { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Cumplimiento> Cumplimiento { get; set; }

    public virtual DbSet<EquipoUtilizado> EquipoUtilizado { get; set; }

    public virtual DbSet<Especificos> Especificos { get; set; }

    public virtual DbSet<EstadoInspeccion> EstadoInspeccion { get; set; }

    public virtual DbSet<EstadoServicio> EstadoServicio { get; set; }

    public virtual DbSet<EstructuraInfome> EstructuraInfome { get; set; }

    public virtual DbSet<Evaluacion> Evaluacion { get; set; }

    public virtual DbSet<FormatoNorma> FormatoNorma { get; set; }

    public virtual DbSet<MenuAcceso> MenuAcceso { get; set; }

    public virtual DbSet<MenuModulo> MenuModulo { get; set; }

    public virtual DbSet<Norma> Norma { get; set; }

    public virtual DbSet<Pda> Pda { get; set; }

    public virtual DbSet<Requisito> Requisito { get; set; }

    public virtual DbSet<Rol> Rol { get; set; }

    public virtual DbSet<Servicio> Servicio { get; set; }

    public virtual DbSet<TerminosYDefiniciones> TerminosYDefiniciones { get; set; }

    public virtual DbSet<TipoFuncionamientoAparato> TipoFuncionamientoAparato { get; set; }

    public virtual DbSet<TipoNorma> TipoNorma { get; set; }

    public virtual DbSet<Titulo> Titulo { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }

    public virtual DbSet<ValoresEspecificos> ValoresEspecificos { get; set; }

    public virtual DbSet<InspeccionNorma> InspeccionNorma { get; set; }

    public virtual DbSet<Fotografias> Fotografias { get; set; }

    public virtual DbSet<ActualizacionesPendientes> ActualizacionesPendientes { get; set; }

    public virtual DbSet<CustomInforme> CustomInforme { get; set; }

    public virtual DbSet<Informe> Informe { get; set; }

    public virtual DbSet<Inspeccion> Inspeccion { get; set; }

    public virtual DbSet<ObservacionTecnica> ObservacionTecnica { get; set; }

    public virtual DbSet<TipoInforme> TipoInforme { get; set; }

    public virtual DbSet<DestinoProyecto> DestinoProyecto { get; set; }

    public virtual DbSet<FotografiaTecnica> FotografiaTecnica { get; set; }

    public virtual DbSet<NormasAsociadas> NormasAsociadas { get; set; }

    public virtual DbSet<DescuentosRecargos> DescuentosRecargos { get; set; }

    public virtual DbSet<DescuentosYRecargos> DescuentosYRecargos { get; set; }

    public virtual DbSet<EstadoCotizacion> EstadoCotizacion { get; set; }

    public virtual DbSet<FormaDePago> FormaDePago { get; set; }

    public virtual DbSet<Hito> Hito { get; set; }

    public virtual DbSet<Moneda> Moneda { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<TipoHito> TipoHito { get; set; }

    public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }

    public virtual DbSet<Marca> Marca { get; set; }

    public virtual DbSet<TipoGasto> TipoGasto { get; set; }

    public virtual DbSet<Settings> Settings { get; set; }

    public virtual DbSet<ListaPrecio> ListaPrecio { get; set; }

    public virtual DbSet<Ciudad> Ciudad { get; set; }

    public virtual DbSet<ListaPrecioCostosLogisticos> ListaPrecioCostosLogisticos { get; set; }

    public virtual DbSet<ArchivoCotizacion> ArchivoCotizacion { get; set; }

    public virtual DbSet<Cotizacion> Cotizacion { get; set; }

    public virtual DbSet<GastoOperacional> GastoOperacional { get; set; }

    public virtual DbSet<ItemCotizacion> ItemCotizacion { get; set; }

    public virtual DbSet<Archivos> Archivos { get; set; }

}

