//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ActualizacionesPendientes
{
    public int ID { get; set; }
    public Nullable<int> PdaID { get; set; }
    public Nullable<int> CaracteristicaID { get; set; }

    public virtual Caracteristica Caracteristica { get; set; }
    public virtual Pda Pda { get; set; }
}

public partial class Aparato
{
    public Aparato()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }

    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class Caracteristica
{
    public Caracteristica()
    {
        this.Cumplimiento = new HashSet<Cumplimiento>();
        this.ActualizacionesPendientes = new HashSet<ActualizacionesPendientes>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> RequisitoID { get; set; }
    public bool Habilitado { get; set; }

    public virtual Requisito Requisito { get; set; }
    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
    public virtual ICollection<ActualizacionesPendientes> ActualizacionesPendientes { get; set; }
}

public partial class Cliente
{
    public Cliente()
    {
        this.Servicio = new HashSet<Servicio>();
    }

    public int ID { get; set; }
    public string Rut { get; set; }
    public string Nombre { get; set; }
    public string Direccion { get; set; }
    public string TelefonoContacto { get; set; }
    public string EmailContacto { get; set; }
    public bool Habilitado { get; set; }

    public virtual ICollection<Servicio> Servicio { get; set; }
}

public partial class Cumplimiento
{
    public Cumplimiento()
    {
        this.Fotografias = new HashSet<Fotografias>();
    }

    public int ID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public Nullable<int> CaracteristicaID { get; set; }
    public Nullable<int> EvaluacionID { get; set; }
    public string Observacion { get; set; }
    public string Fotografia { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }

    public virtual Caracteristica Caracteristica { get; set; }
    public virtual Evaluacion Evaluacion { get; set; }
    public virtual ICollection<Fotografias> Fotografias { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class CustomInforme
{
    public int ID { get; set; }
    public Nullable<int> EstructuraID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public string Texto { get; set; }

    public virtual EstructuraInfome EstructuraInfome { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class DestinoProyecto
{
    public DestinoProyecto()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class EquipoUtilizado
{
    public int ID { get; set; }
    public string Tipo { get; set; }
    public string Identificacion { get; set; }
    public string Usuario { get; set; }
    public string Ident { get; set; }

    public virtual Usuario Usuario1 { get; set; }
}

public partial class Especificos
{
    public Especificos()
    {
        this.ValoresEspecificos = new HashSet<ValoresEspecificos>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }

    public virtual ICollection<ValoresEspecificos> ValoresEspecificos { get; set; }
}

public partial class EstadoInspeccion
{
    public EstadoInspeccion()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class EstadoServicio
{
    public EstadoServicio()
    {
        this.Servicio = new HashSet<Servicio>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Servicio> Servicio { get; set; }
}

public partial class EstructuraInfome
{
    public EstructuraInfome()
    {
        this.CustomInforme = new HashSet<CustomInforme>();
    }

    public int ID { get; set; }
    public Nullable<int> Orden { get; set; }
    public string Título { get; set; }
    public string Texto { get; set; }
    public string Nombre { get; set; }

    public virtual ICollection<CustomInforme> CustomInforme { get; set; }
}

public partial class Evaluacion
{
    public Evaluacion()
    {
        this.Cumplimiento = new HashSet<Cumplimiento>();
    }

    public int ID { get; set; }
    public string Glosa { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> Fase { get; set; }

    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
}

public partial class FormatoNorma
{
    public int ID { get; set; }
    public string Nombre { get; set; }
}

public partial class Fotografias
{
    public int ID { get; set; }
    public string URL { get; set; }
    public Nullable<int> CumplimientoID { get; set; }

    public virtual Cumplimiento Cumplimiento { get; set; }
}

public partial class FotografiaTecnica
{
    public int ID { get; set; }
    public string URL { get; set; }
    public Nullable<int> ObservacionTecnicaID { get; set; }

    public virtual ObservacionTecnica ObservacionTecnica { get; set; }
}

public partial class Informe
{
    public int ID { get; set; }
    public Nullable<System.DateTime> FechaElaboracion { get; set; }
    public Nullable<int> EstadoID { get; set; }
    public string FileName { get; set; }
    public Nullable<int> InspeccionID { get; set; }

    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class Inspeccion
{
    public Inspeccion()
    {
        this.Cumplimiento = new HashSet<Cumplimiento>();
        this.CustomInforme = new HashSet<CustomInforme>();
        this.Informe = new HashSet<Informe>();
        this.InspeccionNorma = new HashSet<InspeccionNorma>();
        this.ValoresEspecificos = new HashSet<ValoresEspecificos>();
        this.ObservacionTecnica = new HashSet<ObservacionTecnica>();
        this.Inspeccion1 = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string IT { get; set; }
    public Nullable<int> AparatoID { get; set; }
    public Nullable<int> TipoFuncionamientoID { get; set; }
    public int EstadoID { get; set; }
    public int ServicioID { get; set; }
    public string Ingeniero { get; set; }
    public System.DateTime FechaCreacion { get; set; }
    public Nullable<System.DateTime> FechaInspeccion { get; set; }
    public string Ubicacion { get; set; }
    public Nullable<System.DateTime> FechaInstalacion { get; set; }
    public string PermisoEdificacion { get; set; }
    public string RecepcionMunicipal { get; set; }
    public Nullable<int> AlturaPisos { get; set; }
    public int Fase { get; set; }
    public string Numero { get; set; }
    public Nullable<System.DateTime> FechaRevision { get; set; }
    public Nullable<System.DateTime> FechaAprobacion { get; set; }
    public Nullable<System.DateTime> FechaEntrega { get; set; }
    public string NombreProyecto { get; set; }
    public string NombreEdificio { get; set; }
    public string Revisador { get; set; }
    public string Aprobador { get; set; }
    public Nullable<int> Calificacion { get; set; }
    public Nullable<int> DiasPlazo { get; set; }
    public Nullable<int> TipoInformeID { get; set; }
    public Nullable<int> InspeccionFase1 { get; set; }
    public string Destinatario { get; set; }
    public Nullable<int> DestinoProyectoID { get; set; }

    public virtual Aparato Aparato { get; set; }
    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
    public virtual ICollection<CustomInforme> CustomInforme { get; set; }
    public virtual EstadoInspeccion EstadoInspeccion { get; set; }
    public virtual ICollection<Informe> Informe { get; set; }
    public virtual ICollection<InspeccionNorma> InspeccionNorma { get; set; }
    public virtual ICollection<ValoresEspecificos> ValoresEspecificos { get; set; }
    public virtual Servicio Servicio { get; set; }
    public virtual TipoFuncionamientoAparato TipoFuncionamientoAparato { get; set; }
    public virtual Usuario Usuario { get; set; }
    public virtual Usuario Usuario1 { get; set; }
    public virtual Usuario Usuario11 { get; set; }
    public virtual ICollection<ObservacionTecnica> ObservacionTecnica { get; set; }
    public virtual TipoInforme TipoInforme { get; set; }
    public virtual ICollection<Inspeccion> Inspeccion1 { get; set; }
    public virtual Inspeccion Inspeccion2 { get; set; }
    public virtual DestinoProyecto DestinoProyecto { get; set; }
}

public partial class InspeccionNorma
{
    public int ID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Norma Norma { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class MenuAcceso
{
    public int ID { get; set; }
    public Nullable<int> MenuModuloID { get; set; }
    public Nullable<int> RolID { get; set; }

    public virtual MenuModulo MenuModulo { get; set; }
    public virtual Rol Rol { get; set; }
}

public partial class MenuModulo
{
    public MenuModulo()
    {
        this.MenuAcceso = new HashSet<MenuAcceso>();
        this.MenuModulo1 = new HashSet<MenuModulo>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public string URL { get; set; }
    public string FontAwesomeIcon { get; set; }
    public Nullable<int> MenuModulosID { get; set; }

    public virtual ICollection<MenuAcceso> MenuAcceso { get; set; }
    public virtual ICollection<MenuModulo> MenuModulo1 { get; set; }
    public virtual MenuModulo MenuModulo2 { get; set; }
}

public partial class Norma
{
    public Norma()
    {
        this.Titulo = new HashSet<Titulo>();
        this.InspeccionNorma = new HashSet<InspeccionNorma>();
        this.TerminosYDefiniciones = new HashSet<TerminosYDefiniciones>();
        this.NormasAsociadas = new HashSet<NormasAsociadas>();
        this.NormasAsociadas1 = new HashSet<NormasAsociadas>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public Nullable<int> TipoNormaID { get; set; }
    public string TituloRegulacion { get; set; }
    public Nullable<bool> Habilitado { get; set; }
    public string ParrafoIntroductorio { get; set; }
    public Nullable<int> TipoInformeID { get; set; }
    public Nullable<bool> Principal { get; set; }

    public virtual ICollection<Titulo> Titulo { get; set; }
    public virtual ICollection<InspeccionNorma> InspeccionNorma { get; set; }
    public virtual TipoInforme TipoInforme { get; set; }
    public virtual ICollection<TerminosYDefiniciones> TerminosYDefiniciones { get; set; }
    public virtual ICollection<NormasAsociadas> NormasAsociadas { get; set; }
    public virtual ICollection<NormasAsociadas> NormasAsociadas1 { get; set; }
    public virtual TipoNorma TipoNorma { get; set; }
}

public partial class NormasAsociadas
{
    public int ID { get; set; }
    public Nullable<int> NormaPrincipalID { get; set; }
    public Nullable<int> NormaSecundariaID { get; set; }

    public virtual Norma Norma { get; set; }
    public virtual Norma Norma1 { get; set; }
}

public partial class ObservacionTecnica
{
    public ObservacionTecnica()
    {
        this.FotografiaTecnica = new HashSet<FotografiaTecnica>();
    }

    public int ID { get; set; }
    public string Texto { get; set; }
    public Nullable<int> InspeccionID { get; set; }

    public virtual Inspeccion Inspeccion { get; set; }
    public virtual ICollection<FotografiaTecnica> FotografiaTecnica { get; set; }
}

public partial class Pda
{
    public Pda()
    {
        this.ActualizacionesPendientes = new HashSet<ActualizacionesPendientes>();
    }

    public int ID { get; set; }
    public string ESN { get; set; }
    public string Usuario { get; set; }

    public virtual Usuario Usuario1 { get; set; }
    public virtual ICollection<ActualizacionesPendientes> ActualizacionesPendientes { get; set; }
}

public partial class Requisito
{
    public Requisito()
    {
        this.Caracteristica = new HashSet<Caracteristica>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> TituloID { get; set; }
    public Nullable<bool> Habilitado { get; set; }

    public virtual ICollection<Caracteristica> Caracteristica { get; set; }
    public virtual Titulo Titulo { get; set; }
}

public partial class Rol
{
    public Rol()
    {
        this.MenuAcceso = new HashSet<MenuAcceso>();
        this.UsuarioRol = new HashSet<UsuarioRol>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }

    public virtual ICollection<MenuAcceso> MenuAcceso { get; set; }
    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
}

public partial class Servicio
{
    public Servicio()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public System.DateTime FechaCreacion { get; set; }
    public int ClienteID { get; set; }
    public string IT { get; set; }
    public Nullable<int> EstadoID { get; set; }

    public virtual Cliente Cliente { get; set; }
    public virtual EstadoServicio EstadoServicio { get; set; }
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class TerminosYDefiniciones
{
    public int ID { get; set; }
    public string Termino { get; set; }
    public string Definicion { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Norma Norma { get; set; }
}

public partial class TipoFuncionamientoAparato
{
    public TipoFuncionamientoAparato()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class TipoInforme
{
    public TipoInforme()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
        this.Norma = new HashSet<Norma>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    public virtual ICollection<Norma> Norma { get; set; }
}

public partial class TipoNorma
{
    public TipoNorma()
    {
        this.Norma = new HashSet<Norma>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    public virtual ICollection<Norma> Norma { get; set; }
}

public partial class Titulo
{
    public Titulo()
    {
        this.Requisito = new HashSet<Requisito>();
    }

    public int ID { get; set; }
    public string Texto { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Norma Norma { get; set; }
    public virtual ICollection<Requisito> Requisito { get; set; }
}

public partial class Usuario
{
    public Usuario()
    {
        this.EquipoUtilizado = new HashSet<EquipoUtilizado>();
        this.Pda = new HashSet<Pda>();
        this.UsuarioRol = new HashSet<UsuarioRol>();
        this.Inspeccion = new HashSet<Inspeccion>();
        this.Inspeccion1 = new HashSet<Inspeccion>();
        this.Inspeccion11 = new HashSet<Inspeccion>();
    }

    public string NombreUsuario { get; set; }
    public string Nombre { get; set; }
    public string Apellido { get; set; }
    public string Pass { get; set; }
    public Nullable<int> EstadoID { get; set; }
    public Nullable<bool> Habilitado { get; set; }
    public string Cargo { get; set; }
    public Nullable<int> NumeroUnico { get; set; }

    public virtual ICollection<EquipoUtilizado> EquipoUtilizado { get; set; }
    public virtual ICollection<Pda> Pda { get; set; }
    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    public virtual ICollection<Inspeccion> Inspeccion1 { get; set; }
    public virtual ICollection<Inspeccion> Inspeccion11 { get; set; }
}

public partial class UsuarioRol
{
    public int ID { get; set; }
    public string Usuario { get; set; }
    public Nullable<int> Rol { get; set; }

    public virtual Rol Rol1 { get; set; }
    public virtual Usuario Usuario1 { get; set; }
}

public partial class ValoresEspecificos
{
    public int ID { get; set; }
    public Nullable<int> EspecificoID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public string Valor { get; set; }

    public virtual Especificos Especificos { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}
